var flub = new Flub('#sandbox-wheel', {
  min: 0,
  max: 360,
  speed: 800,
  dispatch: true,
  sync: false,
  elastic: true
}),
  a = document.querySelector('#add'),
  ul = document.querySelector('#menu'),
  icons = [
    "adn",
    "android",
    "angellist",
    "apple",
    "behance",
    "behance-square",
    "bitbucket",
    "bitbucket-square",
    "btc",
    "buysellads",
    "cc-amex",
    "cc-discover",
    "cc-mastercard",
    "cc-paypal",
    "cc-stripe",
    "cc-visa",
    "codepen",
    "connectdevelop",
    "css3",
    "dashcube",
    "delicious",
    "deviantart",
    "digg",
    "dribbble",
    "dropbox",
    "drupal",
    "empire",
    "facebook",
    "facebook-official",
    "facebook-square",
    "flickr",
    "forumbee",
    "foursquare",
    "git",
    "git-square",
    "github",
    "github-square",
    "google",
    "google-plus",
    "google-plus-square",
    "google-wallet",
    "gratipay",
    "hacker-news",
    "html5",
    "instagram",
    "ioxhost",
    "joomla",
    "jsfiddle",
    "lastfm",
    "lastfm-square",
    "leanpub",
    "linkedin",
    "linkedin-square",
    "linux",
    "maxcdn",
    "meanpath",
    "medium",
    "openid",
    "pagelines",
    "paypal",
    "pied-piper",
    "pied-piper-alt",
    "pinterest",
    "pinterest-p",
    "pinterest-square",
    "qq",
    "rebel",
    "reddit",
    "reddit-square",
    "renren",
    "sellsy",
    "share-alt",
    "share-alt-square",
    "shirtsinbulk",
    "simplybuilt",
    "skyatlas",
    "skype",
    "slack",
    "slideshare",
    "soundcloud",
    "spotify",
    "stack-exchange",
    "stack-overflow",
    "steam",
    "steam-square",
    "stumbleupon",
    "stumbleupon-circle",
    "tencent-weibo",
    "trello",
    "tumblr",
    "tumblr-square",
    "twitch",
    "twitter",
    "twitter-square",
    "viacoin",
    "vimeo-square",
    "vine",
    "vk",
    "weibo",
    "weixin",
    "whatsapp",
    "windows",
    "wordpress",
    "xing",
    "xing-square",
    "yahoo",
    "yelp",
    "youtube",
    "youtube-play",
    "youtube-square"
  ],
  addIcon = function() {
    var li = document.createElement('li');
    li.innerHTML = '<a href="#"><i class="fa fa-' + icons[~~(Math.random() * icons.length)] + '"></i></a>';
    ul.appendChild(li);
    flub.populate();
  };
for (var i = 0; i < 12; i++)
  addIcon();
a.addEventListener('click', function(e) {
  addIcon();
  flub.position();
  return false;
}, false);
